version: '3.8'

services:
  web:
    build: .
    ports:
      - "7000:7000"
    environment:
      # You can add environment variables here if needed
      - FLASK_ENV=development
    restart: unless-stopped
